# Generated by Django 5.1.1 on 2024-09-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventorymanager", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
