# Generated by Django 5.1.1 on 2026-03-28 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='telegram',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_email',
            new_name='contact_telegram',
        ),
        migrations.AddField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventorymanager.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('part', 'Запчасть'), ('service', 'Услуга')], default='part', max_length=48),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventorymanager.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventorymanager.supplier'),
        ),
    ]
