# Generated by Django 5.1.1 on 2026-04-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0007_remove_order_order_date_customer_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
