# Generated by Django 5.1.1 on 2026-04-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0008_rename_first_name_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='client',
            new_name='customer',
        ),
    ]
