# Generated by Django 5.1.1 on 2026-04-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0010_alter_order_employee_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='telegram',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
