# Generated by Django 5.1.1 on 2026-04-26 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0011_alter_customer_telegram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название кассы')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Расположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Начальный остаток')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
            },
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.CharField(choices=[('scooter', 'Самокат'), ('ebike', 'Электровелосипед'), ('bicycle', 'Велосипед'), ('monowheel', 'Моноколесо'), ('other', 'Другое')], default='bicycle', max_length=100, verbose_name='Тип транспорта'),
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], max_length=10, verbose_name='Способ оплаты')),
                ('reason', models.CharField(max_length=200, verbose_name='Основание')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён')], default='confirmed', max_length=10, verbose_name='Статус')),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер чека')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventorymanager.cashregister', verbose_name='Касса')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventorymanager.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Кассовая операция',
                'verbose_name_plural': 'Кассовые операции',
                'ordering': ['-created_at'],
            },
        ),
    ]
