# Generated by Django 5.1.1 on 2026-04-26 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0012_cashregister_alter_transport_transport_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashtransaction',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventorymanager.order', verbose_name='Заказ (для расходов)'),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод'), ('online', 'Онлайн')], max_length=10, verbose_name='Способ оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Принял оплату')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventorymanager.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Оплата заказа',
                'verbose_name_plural': 'Оплаты заказов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='order_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transaction', to='inventorymanager.orderpayment', verbose_name='Оплата заказа'),
        ),
    ]
