# Generated by Django 5.1.1 on 2026-05-01 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0013_remove_cashtransaction_receipt_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='transport_photos/%Y/%m/%d/', verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_images', to='inventorymanager.order', verbose_name='Заказ (в котором добавили фото)')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventorymanager.transport', verbose_name='Транспорт')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Фото транспорта',
                'verbose_name_plural': 'Фотографии транспорта',
                'ordering': ['-created_at'],
            },
        ),
    ]
